---
apiVersion: networking.k8s.io/v1	
kind: Ingress
metadata:
  annotations: 
    key: value
  labels: 
    environment: dev
    app: nginx
    name: nginx
  namespace: dev  
spec:
  service: 
    name: nginx
    port: 
      name: nginx
      number: 80
  
  
                  
                
  